### ISSUE TITLE
IDP not authenticated while SP is, on external SAMP2p

### ISSUE THREAD

**Issue by binbsr** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#5]
I am just using the sample repo (No customization) given here with demo license. Got interesting behavior of IDP.
Steps:
1. Navigate to SP (port 5001)
2. Navigate to login page and click external SAML2p
3. Its redirects us to idp (port 5000) login page and enter credentials (alice-alice)
4. Upon clicking login, it redirect back to sp page, SP is logged in
5. Navigate to idp and no track of just logged in user alice ("idsrv" cookie is there but no "idsrv.session")

Following is the log of IDP, moment before it says logged in and after navigating/refreshing the idp page, its unauthenticated.
![samlpluginbug](https://user-images.githubusercontent.com/1488017/44972057-945ea600-af77-11e8-91ab-9934da34fc0f.png)
@scottbrady91 Any insight on this please.

**Comment by scottbrady91** [comment]
It's because both IdentityServer instances are running on localhost, and since they're using the same cookie names, they are overwriting each other's cookies.

I've changed the name of the IdP cookie to demo that functionality: https://github.com/RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration/blob/57568185fc3cf6560f0541f54c57dfcf00fc67a5/idp/Startup.cs#L60

**Comment by binbsr** [comment]
Thanks @scottbrady91, Your change worked. I though port numbers would make difference for cookie management but seems it just goes for host name.
